### ISSUE TITLE
removing object cap?

### ISSUE THREAD

**Issue by TheThouZands** [Waffle1434/Halo-Reach-Forge-Assistant#5]
the editor has a cap of 650 objects, i haven't read everything, but i'm guessing it most likely is to not overload certain part of the process, which if it does it'd prolly corrupt the file that is being worked on; however, if that is the case, i would like to have the posibility to have it removed; as in a lot of instances, 650 object is really not close to enough.

**Comment by Waffle1434** [comment]
Unfortunately the 650 object cap is a very hardcoded limit of Halo Reach. Bungie only reserved space for 650 objects in RAM and the `.mvar` files. If you were to attempt to have more than 650, it would overwrite memory completely unrelated and it has crashed my game in my attempts.

The only way it'd be possible is if 343 patches the game to support more (it'd be easiest for them since they have the source code, but it still may not be trivial for them). Alternatively someone could hypothetically modify the game's code to increase the hardcoded limit. That would be very difficult, as they'd have to reverse engineer the assembly code and find all the places the 650 limit is in place, and even if they managed to do it, everyone who wanted to play with you would need to have that mod as well.

**Comment by azeroverdose** [comment]
Is this still the case?
